version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:10.9.0-browsers

jobs:
  ncuu:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: ncu -u
          command: npm run ncuu
  commit:
      <<: *defaults
      steps:
        - run:
            name: commit
            command: |
              git config user.email "jbcazaux@gmail.com"
              git config user.name "circleci bot"
              git commit --allow-empty -m "update lib versions"
              git push -q https://${GITHUB_TOKEN}@github.com/jbcazaux/formation-reactjs-es6.git master

  build:
    <<: *defaults

    steps:
    - checkout

    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "package.json" }}

        - v2-dependencies-

    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v2-dependencies-{{ checksum "package.json" }}

    - run:
        name: build TPs
        command: npm run testci

    - run:
        name: launch http-server
        command: npm run httpserver
        background: true

    - run:
        name: run tests
        command: node ./puppeteer/openpage.js

    - run:
        name: kill server
        command: pkill node

    - persist_to_workspace:
        root: ~/repo
        paths: .

workflows:
  version: 2
  build-tps:
    jobs:
    - build:
        filters:
          branches:
            only:
              - master
              - test-ci
  test-updates:
    triggers:
    - schedule:
        cron: "2 30 * * *"
        filters:
          branches:
            only:
            - master
    jobs:
      - ncuu
      - build:
          requires:
            - ncuu
      - commit:
          requires:
          - build