name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.17.0-chrome106

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress/cypress.config.js
          install-command: npm ci -f --no-audit --ignore-scripts
          start: npm run starti
          wait-on: 'http://localhost:8080'
          browser: chrome
      - name: Archive test screenshots
        uses: actions/upload-artifact@v2.2.4
        with:
          name: screenshots
          path: cypress/screenshots
        if: ${{ failure() }}
