name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master

env:
  CYPRESS_CACHE_FOLDER: ~/cache/Cypress npm install

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-${{ hashFiles('package-lock.json') }}
      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v3
        with:
          path: ~/cache/Cypress
          key: cypress-cache-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci -f --no-audit --ignore-scripts
      - name: Run unit tests of TP07
        run: ./node_modules/.bin/jest --roots TPs/solutions/TP-07
      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress/cypress.config.js
          install-command: npx cypress install
          start: npm run starti
          wait-on: 'http://localhost:8080'
          browser: chrome
      - name: Archive test screenshots
        uses: actions/upload-artifact@v2.2.4
        with:
          name: screenshots
          path: cypress/screenshots
        if: ${{ failure() }}
